# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semana',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
